Feroxbuster:
  api_key:
    required: false
  binary: feroxbuster
  category: fuzzing
  check_cmd: feroxbuster --version
  description: A fast, simple, recursive content discovery tool
  execution_time: 900
  name: Feroxbuster
  recommendation_score: 89
  target_types:
  - webapp
