Semgrep:
  api_key:
    description: API token for Semgrep App integration
    env_var: SEMGREP_APP_TOKEN
    required: false
    url: https://semgrep.dev/
  binary: semgrep
  category: sast
  check_cmd: semgrep --version
  description: Static Application Security Testing with simple patterns
  execution_time: 300
  name: Semgrep
  recommendation_score: 90
  target_types:
  - code
