Trufflehog:
  api_key:
    required: false
  binary: trufflehog
  category: sast
  check_cmd: trufflehog --version
  description: Searches through git repositories for secrets
  execution_time: 300
  name: Trufflehog
  recommendation_score: 91
  target_types:
  - code
  - repository
