# Supply Chain Security Assessment Scan Mode for Sniper
# This defines a specialized scan mode for assessing supply chain security risks

supply_chain:
  name: supply_chain
  description: "Specialized scan for software supply chain security assessment, focusing on dependencies and package vulnerabilities"
  target_types: ["domain", "url", "ip", "repository", "package"]
  modules:
    - technologies
    - web
    - ports
  settings:
    max_threads: 8
    timeout: 4800  # 80 minutes
    retries: 2
    scan_depth: comprehensive
  tools:
    # Repository and package scanning
    wappalyzer:
      enabled: true
      options:
        dependencies: true  # Focus on dependency detection
    
    # Network security scanning
    nmap:
      enabled: true
      options:
        ports: "21,22,80,443,3000,5000,8080,8443,9000"  # Common development and repository ports
        timing_template: 3
        scripts: "vuln,auth"
    
    # Web security scanning
    zap:
      enabled: true
      options:
        active_scan: true
        api_scan: true
        ajax_spider: true
        scan_policy: "Supply-Chain-Policy"  # Custom policy focusing on supply chain attacks
    
    # Vulnerability scanning 
    nuclei:
      enabled: true
      options:
        templates: "cves,vulnerabilities,exposed-panels,misconfigurations"
        severity: "critical,high,medium"
        tag: "supply-chain,package-manager,ci"
    
    # Dependency scanning (special options for dependency checking)
    dependency_check:
      enabled: true
      options:
        scan_type: "all"
        check_for_outdated: true
        check_for_vulnerabilities: true
        scan_depth: 3  # How deep to scan nested dependencies
    
    # Secret scanning
    gitleaks:
      enabled: true
      options:
        scan_history: true
        config_path: "supply-chain-rules.toml"
        severity: "high,medium"
    
    # Container image scanning
    trivy:
      enabled: true
      options:
        scan_type: "image,fs"
        severity: "CRITICAL,HIGH,MEDIUM"
        ignore_unfixed: false
        timeout: 600 